AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Http Api

Parameters:
  AppConfigAppId:
    Type: String
    Description: AppConfig Application Id
  AppConfigAppEnvironmentId:
    Type: String
    Description: AppConfig Application Environment Id
  AppConfigtId:
    Type: String
    Description: AppConfig Id
  RecipeConfigPath:
    Type: String
    Description: config path in AppConfig
    
Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi

  BlazorAppConfigFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: "BlazorAppConfig.Function::BlazorAppConfig.Function.Function::FunctionHandler"
      Runtime: dotnet6
      CodeUri: ""
      Description: Retrieves Recipe Flag configuration
      MemorySize: 256
      Timeout: 600
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:434848589818:layer:AWS-AppConfig-Extension:82
      Policies:        
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - appconfig:GetLatestConfiguration
                - appconfig:StartConfigurationSession
              Resource: !Sub 'arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${AppConfigAppId}/environment/${AppConfigAppEnvironmentId}/configuration/${AppConfigtId}'
      Environment:
        Variables:
          RECIPE_CONFIG_PATH: !Ref RecipeConfigPath
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /config
            Method: get
            ApiId: !Ref HttpApi
Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi